# Generated by Django 2.1 on 2019-04-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20190419_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_boda',
            name='Descripcion',
            field=models.TextField(max_length=2000),
        ),
    ]
